#!/bin/bash

title=
header=
button1=
button2=
button3=
button4=
footer=

while getopts .1:2:3:4:t:h:f:. OPTION
do
  case $OPTION in
    1)
      button1=$OPTARG
      ;;
    2)
      button2=$OPTARG
      ;;
    3)
      button3=$OPTARG
      ;;
    4)
      button4=$OPTARG
      ;;
    t)
      title=$OPTARG
      ;;
    h)
      header=$OPTARG
      ;;
    f)
      footer=$OPTARG
      ;;
  esac
done

/usr/bin/convert -size 600x800 canvas:white -depth 8 -font /tmp/sdcache/DroidSansFallback.ttf \
-pointsize 45 \
-draw "gravity North text 0,0 '$title'" \
-pointsize 26 \
-draw "gravity West text 0,-115 '$button1' " \
-draw "gravity East text 0,-85  '$button2' " \
-draw "gravity West text 0,105  '$button3' " \
-draw "gravity East text 0,135  '$button4' " \
-gravity north \
-annotate +0+80 "$header" \
-gravity south \
-annotate +0+0 "$footer" \
 rgb:/tmp/fb.raw && /bin/to565 /tmp/fb.raw /dev/graphics/fb0 

